# Cloud
[[main]]
  name = "Cloud"
  identifier = "cloud"
  url = "/cloud/"
  weight = 10
[[main]]
  parent = "cloud"
  name   = "Azure"
  url    = "/cloud/azure/"
  weight = 11
[[main]]
  parent = "cloud"
  name   = "Ovh"
  url    = "/cloud/ovh/"
  weight = 12

# k8s
[[main]]
  name = "Kubernetes"
  url  = "/kubernetes/"
  weight = 20

# Platform
[[main]]
  name = "Platform"
  identifier = "platform"
  url = "/platform/"
  weight = 30
[[main]]
  parent = "platform"
  name   = "IaC"
  url    = "/platform/iac/"
  weight = 31

[[main]]
  parent = "platform"
  name   = "CI/CD"
  url    = "/platform/ci-cd/"
  weight = 32

[[main]]
  parent = "platform"
  name   = "Ansible"
  url    = "/platform/ansible/"
  weight = 33

[[main]]
  parent = "platform"
  name   = "DevOps"
  url    = "/platform/devops/"
  weight = 34

# Programming
[[main]]
  name = "Programming"
  identifier = "programming"
  url    = "/programming/"
  weight = 40
[[main]]
  parent = "programming"
  name   = "Python"
  url    = "/programming/python/"
  weight = 41

[[main]]
  parent = "programming"
  name   = ".NET"
  url    = "/programming/dotnet/"
  weight = 42

[[main]]
  parent = "programming"
  name   = "Bash"
  url    = "/programming/bash/"
  weight = 44

# Security
[[main]]
  name = "Security"
  url  = "/security/"
  weight = 50

# Linux
[[main]]
  name = "Linux"
  url  = "/linux/"
  weight = 60



# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "X"
#   url = "https://x.com/"

[[main]]
  name = "About Me"
  url  = "/about-me/"
  weight = 100

[[main]]
  name = "Contact Me"
  url  = "/contact-me/"
  weight = 110

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/coumarane"
# [[social]]
#   name = "X"
#   weight = 2
#   url = "https://x.com/coumarane_c"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/coumarane-couppane-712a2415"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"