baseURL = "https://iamcoumar.com/"
languageCode = "en-us"
title = "iamcoumar"
theme = ["hugo-clarity"]

[params]
  subtitle = 'The Bbest Blog for DevOps Engineer'
  [params.contact]
    email = 'c.coumarane@gmail.com'
    phone = '+33 6 45 35 60 89'


